name: Ccompile

on:
  push:
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:
    

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

   

    - name: Compile doom
      run: |
        make -f Makefile.ps2
        ls
    
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: doom-${{ steps.slug.outputs.sha8 }}
        path: *.elf

#    - name: Create release
#      if: github.ref == 'refs/heads/master'
#      uses: marvinpinto/action-automatic-releases@latest
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        automatic_release_tag: "latest"
#        title: "Latest  build"
#        files: *.elf
